[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
span = { path = "../../crates/span" }
example = {path = "../example" }
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
